//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int DepositCode { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<int> MarketPrice { get; set; }
    }
}
