//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int DepositCode { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<int> MarketPrice { get; set; }
    }
}
