//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Id { get; set; }
        public Nullable<int> PointCode { get; set; }
        public Nullable<int> DepositCode { get; set; }
        public string DevelopmentMethod { get; set; }
        public Nullable<int> Opening { get; set; }
        public Nullable<int> Closing { get; set; }
        public Nullable<int> Reserves { get; set; }
        public Nullable<int> CostPrice { get; set; }
    }
}
