//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Id { get; set; }
        public Nullable<int> PointCode { get; set; }
        public Nullable<int> DepositCode { get; set; }
        public string DevelopmentMethod { get; set; }
        public Nullable<int> Opening { get; set; }
        public Nullable<int> Closing { get; set; }
        public Nullable<int> Reserves { get; set; }
        public Nullable<int> CostPrice { get; set; }
    }
}
