//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class minerals2Entities1 : DbContext
    {
        private static minerals2Entities1 _context;

        public static minerals2Entities1 GetContext()
        {
            if (_context == null)
                _context = new minerals2Entities1();
            return _context;
        }
        public minerals2Entities1()
            : base("name=minerals2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Field> Field { get; set; }
    }
}
