//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minerals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class minerals2Entities1 : DbContext
    {
        public minerals2Entities1()
            : base("name=minerals2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Field> Field { get; set; }
    }
}
